services:
  
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - C:\xampp\htdocs\entrega\:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: entrega
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

